name: Symphony CMS
description: An open source CMS.
url: http://getsymphony.com/
baseurl: "/docs.getsymphony.com"
markdown: redcarpet
highlighter: pygments
exclude:
- README.md
- CONTRIBUTING.md
gems:
- jekyll-redirect-from
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "docs"