name: Symphony CMS
description: An open source CMS.
url: http://getsymphony.com/
baseurl: "/docs.getsymphony.com"
markdown: redcarpet
highlighter: pygments
exclude:
- README.md
gems:
- jekyll-redirect-from