name: Symphony CMS
description: An open source CMS.
url: http://getsymphony.com/
baseurl: "/docs.getsymphony.com"
markdown: redcarpet
highlighter: pygments
exclude:
- README.md
gems:
- jekyll-redirect-from
collections:
  articles:
    output: true
    title: Articles
  book:
    output: true
    title: Book
  concepts:
    output: true
    title: Concepts
  guides:
    output: true
    title: Guides
  tutorials:
    output: true
    title: Tutorials
  working:
    output: true
    title: Working
